# Generated by Django 5.0.3 on 2024-05-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('schedule_date', models.DateTimeField()),
                ('status', models.CharField(max_length=200)),
                ('tv_station', models.CharField(max_length=200)),
                ('week', models.IntegerField()),
                ('league', models.CharField(choices=[('nfl', 'NFL'), ('ncaa', 'NCAA')], max_length=10)),
                ('home_team_name', models.CharField(max_length=200)),
                ('home_team_spread', models.FloatField()),
                ('home_team_score', models.IntegerField()),
                ('home_team_record', models.CharField(max_length=200)),
                ('away_team_name', models.CharField(max_length=200)),
                ('away_team_spread', models.FloatField()),
                ('away_team_score', models.IntegerField()),
                ('away_team_record', models.CharField(max_length=200)),
            ],
        ),
    ]
