# Generated by Django 5.0.3 on 2024-04-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_retriever', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
