# Generated by Django 5.0.3 on 2024-04-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_retriever', '0002_game_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.CharField(choices=[('nfl', 'NFL'), ('ncaa', 'NCAA')], default='nfl'),
            preserve_default=False,
        ),
    ]
